### ISSUE TITLE
Jyotshna please change the fonts 

### ISSUE THREAD

**Issue by bhattaprii** [bhattaprii/E-Challan-system#1]
Try exploring fonts such poppins, Saira and please upload the changes as soon as possible.

**Comment by JyotshnaT** [comment]
![recent](https://user-images.githubusercontent.com/103411907/162702338-bc0b3b29-1f03-48e0-8899-48a0aad3aff4.jpg)
![recent2](https://user-images.githubusercontent.com/103411907/162702345-6dcffef9-eb81-4647-b3a0-2762e00f1f58.jpg)
