### ISSUE TITLE
Aisha and Paleswan please check the delete traffic dashboard #2

### ISSUE THREAD

**Issue by bhattaprii** [bhattaprii/E-Challan-system#2]
Delete traffic doesn't delete traffics on the dashboard please check if there is any error.

**Comment by paleswan** [comment]
The issue has been tracked and solve. Please check it.
![Screenshot (97)](https://user-images.githubusercontent.com/84459910/162757332-d004fd2e-f52f-407f-83f6-00086987332b.png)
