### ISSUE TITLE
Jyotsna, change the fonts of information page.

### ISSUE THREAD

**Issue by bhattaprii** [bhattaprii/E-Challan-system#4]

**Comment by JyotshnaT** [comment]
![issue ](https://user-images.githubusercontent.com/103411907/168511990-bb915ff8-b356-45ed-9cd5-1954179dbca4.jpg)
![ISSUE](https://user-images.githubusercontent.com/103411907/168512009-2f2e02ab-5f9c-412b-92ff-70fa41efb960.jpg)

**Comment by JyotshnaT** [comment]
![issue ](https://user-images.githubusercontent.com/103411907/168512095-c60da847-cd9b-42f5-a141-3b89c1706911.jpg)
![INFOPAGE](https://user-images.githubusercontent.com/103411907/168512115-1b3a5980-dca0-4fe2-bd05-9af1fa8c590c.jpg)

**Comment by JyotshnaT** [comment]
I resolved the issue with the information page by changing it to a dark theme that fits our system typefaces and makes the content visible and clear.
